# Generated by Django 4.1.5 on 2023-02-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app8', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=8)),
                ('Name', models.CharField(max_length=8)),
                ('Price', models.IntegerField()),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
